import BillItem from "../model/BillItem";

class Bill {
  billno: string;
  billdate: number;
  billtoyear: string;
  billtoqtr: string;
  billperiod: string;
  taxpayername: string;
  taxpayeraddress: string;
  taxpayerobjid: string;
  tdno: string;
  fullpin: string;
  rputype: string;
  lguname: string;
  barangay: string;
  titleno: string | null;
  classification: string;
  cadastrallotno: string;
  administratorname: string | null;
  administratoraddress: string | null;
  ownername: string;
  totalav: number;
  totalmv: number;
  totalareaha: number;
  totalareasqm: number;
  total: number;
  sef: number;
  sefint: number;
  sefdisc: number;
  sefnet: number;
  sefdp: number;
  basic: number;
  basicint: number;
  basicdisc: number;
  basicnet: number;
  basicdp: number;
  amount: number;
  fromyear: number;
  fromqtr: number;
  toyear: number;
  toqtr: number;
  validuntil: string;
  txntypename: string;
  items: BillItem[];

  public constructor(data: any) {
    this.billno = data.info.billno ?? "";
    this.billdate = data.info.billdate ?? 0;
    this.billtoyear = data.info.billtoyear ?? "";
    this.billtoqtr = data.info.billtoqtr ?? "";
    this.billperiod = data.info.billperiod ?? "";
    this.taxpayername = data.info.taxpayer?.name ?? "";
    this.taxpayeraddress = data.info.taxpayer?.address ?? "";
    this.taxpayerobjid = data.info.taxpayer?.objid ?? "";
    this.tdno = data.info.tdno ?? "";
    this.fullpin = data.info.fullpin ?? "";
    this.rputype = data.info.rputype ?? "";
    this.lguname = data.info.lguname ?? "";
    this.barangay = data.info.barangay ?? "";
    this.titleno = data.info.titleno ?? "";
    this.classification = data.info.classification ?? "";
    this.cadastrallotno = data.info.cadastrallotno ?? "";
    this.administratorname = data.info.administrator?.name ?? "";
    this.administratoraddress = data.info.administrator?.address ?? "";
    this.ownername = data.info.owner?.name ?? "";
    this.totalav = data.info.totalav ?? 0;
    this.totalmv = data.info.totalmv ?? 0;
    this.totalareaha = data.info.totalareaha ?? 0;
    this.totalareasqm = data.info.totalareasqm ?? 0;
    this.total = data.info.totals.total ?? 0;
    this.sef = data.info.totals.sef ?? 0;
    this.sefint = data.info.totals.sefint ?? 0;
    this.sefdisc = data.info.totals.sefdisc ?? 0;
    this.sefnet = data.info.totals.sefnet ?? 0;
    this.sefdp = data.info.totals.sefdp ?? 0;
    this.basic = data.info.totals.basic ?? 0;
    this.basicint = data.info.totals.basicint ?? 0;
    this.basicdisc = data.info.totals.basicdisc ?? 0;
    this.basicnet = data.info.totals.basicnet ?? 0;
    this.basicdp = data.info.totals.basicdp ?? 0;
    this.amount = data.info.amount ?? 0;
    this.fromyear = data.info.fromyear ?? 0;
    this.fromqtr = data.info.fromqtr ?? 0;
    this.toyear = data.info.toyear ?? 0;
    this.toqtr = data.info.toqtr ?? 0;
    this.validuntil = data.info.validuntil ?? "";
    this.txntypename = data.info.txntypename ?? "";
    this.items = (data.info.items || []).map((item: any) => new BillItem(item));
  }
}

export default Bill;
